# Generated by Django 4.2.3 on 2023-07-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_notes_options_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='if_finished',
            new_name='is_finished',
        ),
    ]
